import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NewComponent from "@/components/NewComponent";
import NewsSection from "@/components/NewsSection";
import Navbar from "@/components/Navbar";
import cover from "../../public/cover.png";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <div style={{ width: "100%", height: "100%" }}>
        <Image src={cover} layout="fill" objectFit="contain" />
      </div>
      <NewsSection />
      {/* <NewComponent text="อะไรซักอย่างที่มันไม่บัค" /> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
    </>
  );
}
